# OpenShift-specific targets and defaults, included after the upstream Makefile.

test-e2e-ocp: test-e2e-handler-ocp # deprecated. Use test-e2e-handler-ocp instead

test-e2e-handler-ocp:
	./hack/ocp-e2e-tests-handler.sh

test-e2e-operator-ocp:
	./hack/ocp-e2e-tests-operator.sh
